name: lod_flutter
description: A new Flutter package project.
version: 0.0.2
author: "Lawyers on Demand"
homepage: "https://lodlaw.com"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0 <3.32.7"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.17.0
  image_picker: ^0.8.2
  animations: ^2.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
